# Generated by Django 4.2.7 on 2023-11-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('passed_year', models.DateField()),
            ],
        ),
    ]
